#pragma once

namespace Errors
{

// The SCARD variables are HRESULT, ie long
const DWORD SC_E_INVALID_HANDLE = (DWORD)SCARD_E_INVALID_HANDLE;
const DWORD SC_E_INVALID_PARAMETER = (DWORD)SCARD_E_INVALID_PARAMETER;
const DWORD SC_E_UNSUPPORTED_FEATURE = (DWORD)SCARD_E_UNSUPPORTED_FEATURE;
const DWORD SC_W_CHV_BLOCKED = (DWORD)SCARD_W_CHV_BLOCKED;
const DWORD SC_W_WRONG_CHV = (DWORD)SCARD_W_WRONG_CHV;
const DWORD SC_W_SECURITY_VIOLATION = (DWORD)SCARD_W_SECURITY_VIOLATION;
const DWORD SC_E_UNKNOWN_CARD = (DWORD)SCARD_E_UNKNOWN_CARD;
const DWORD SC_E_DIR_NOT_FOUND = (DWORD)SCARD_E_DIR_NOT_FOUND;
const DWORD SC_E_FILE_NOT_FOUND = (DWORD)SCARD_E_FILE_NOT_FOUND;
const DWORD SC_E_NO_KEY_CONTAINER = (DWORD)SCARD_E_NO_KEY_CONTAINER;
const DWORD SC_E_INSUFFICIENT_BUFFER = (DWORD)SCARD_E_INSUFFICIENT_BUFFER;
const DWORD SC_F_COMM_ERROR = (DWORD)SCARD_F_COMM_ERROR;
const DWORD SC_E_UNEXPECTED = (DWORD)SCARD_E_UNEXPECTED;
const DWORD SC_E_NO_MEMORY = (DWORD)SCARD_E_NO_MEMORY;
const DWORD SC_E_WRITE_TOO_MANY = (DWORD)SCARD_E_WRITE_TOO_MANY;
const DWORD SC_W_CANCELLED_BY_USER = (DWORD)SCARD_W_CANCELLED_BY_USER;
const DWORD SC_E_NO_ACCESS = (DWORD)SCARD_E_NO_ACCESS;

}
